import { Inter } from "next/font/google";

import "./globals.css";
import Header from "./Componentes/Header";
import ProductoProvider from "./Context/ProductContext";
import { AuthProvider } from "./Context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ProductoProvider>
            <Header />
            {children}
          </ProductoProvider>
        </AuthProvider>
      </body>
    </html>
  );
}


